apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AIOSTREAM_ADDON_PASSWORD: ENC[AES256_GCM,data:PEEbfNXPXRjQbzV/,iv:dLQHrM9/+PkkFYYNJ95k4yE96+lvSZJ98Qs1ZOaFNv4=,tag:DOwSS5A6S2hyI8RKLUa1ig==,type:str]
    AIOSTREAM_SECRET_KEY: ENC[AES256_GCM,data:RP5u4CdWe0SfNQzrwowHRLE8tdec7eJE0grb2Li+gz2Qu4jFAIdT/qa3/YWapiceUKUCfRQuPvoKdxZfsmTftg==,iv:mIMYgQGlwJWE44n975YvUTaj/ktG9Pi3txY9LtYU+/Y=,tag:Ne7We95zukLDTFzzjywjqw==,type:str]
    SPOTTARR_USENET_PASSWORD: ENC[AES256_GCM,data:OHXff2sEkYM=,iv:GjzgpLSNWSOKkRChTb0B+21RU3G3Dqv5jkllFVleLbs=,tag:6kCQ0LxbsoTBemrQfq3xLw==,type:str]
    SPOTTARR_USENET_USERNAME: ENC[AES256_GCM,data:sqHh684MV1R9gw==,iv:s4j57qsaYi1L8bovybPULfUmvQ2w8REllBpng5/5C7Q=,tag:mylJandCOCXsQ96gp7Ilbg==,type:str]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:1wGlXqHfDs6F5gi9h6TIzj0ea5Oi4Kn5MVAcS2A7j3sFKBlJls0J6w==,iv:bicXIDUJEMTmSsiigB2gmYTEPs0WZqlSasy1y9qRzfI=,tag:2opkrIOyDTIrm0xUvmcvSw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:7w6+GND3Gn4dxzKjyLOJn3VgcxdXQiKXCgBS/KBvBG+LAImkkO/1HQNylWU=,iv:/iFb7VpCJk2uLTB+/YSOnRU7sGQzrZlJaxAGjbD+Jec=,tag:j6X8rer+GXmy9UzLl88lXA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LU/2uGvITPY7wMY7uCQPg2HEZA==,iv:T1mJ/pO0M8mOJkjpTRwfLeGikrU41mnbiINnLEVjAN0=,tag:lDhVp1eASHh2g/i5J/1GEA==,type:str]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:PZHs5dBhoMTVKkL9BQ==,iv:OSFjvmKsV+P7Wjw/dt9tm8U/Va9QrWTg9x0bos1D0ro=,tag:bnGdb+wA9nZrUpiEm4qrKg==,type:str]
    TZ: ENC[AES256_GCM,data:Y2lAEeSoJaA1avxMIpj8aw==,iv:i78uzvOgEDejQYFJdN1NRWfC8+x8Ny00fXnF2nWdkVU=,tag:4PhwK+rnP5GhFCzAvYBkBQ==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:+nMuzKg=,iv:7CpiGITJ8fgsppJKLkR6v36gvgttQ+nyTIXOXzxHV5U=,tag:8ofrN+ibW7Pdq8D7JRPhIw==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:7rAn+HdzZCEbz6HskV+IUQd1CFtTxQ==,iv:RppIfLDpLN1oBJiGmZ06S6XrPjTkVW6zB5CZuI+ic4w=,tag:1ptuKC4g+yhD90w7ZKXQlA==,type:str]
    CAMERA_ADMIN_USERNAME: ENC[AES256_GCM,data:uDfE/i0=,iv:jFlrG6PKnhgDyfitIwvjxDn2LNJ/6+DD60dqI+bO3bg=,tag:A6QCgbjvyXYJDm+eM95aGw==,type:str]
    CAMERA_ADMIN_PASSWORD: ENC[AES256_GCM,data:1x6NA2f9Ig9/9DCx,iv:ntQPYl+F/yINdcPA5awFjV6Bvsz3zrPLlilWQkyO1c0=,tag:+/7DFzYG6mscVH7ijWERSA==,type:str]
    KEYCLOAK_ADMIN_USERNAME: ENC[AES256_GCM,data:xK3oBtw=,iv:+UUo3h3mWGcITlktrvZNmbRMk4i6uoVo5Rw4D//NHUo=,tag:bAMBzZR9tdfY364V0qK4Sg==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:XXEyzXKnJiic3hr2,iv:Gx+gl/g/X0yiSkRGZOQrCTliFBtVIRRoVtE9aqha1lg=,tag:auY1Wjqe1FkJpqiKNH/0Ag==,type:str]
    KEYCLOAK_DB_PASSWORD: ENC[AES256_GCM,data:CL92VqWTrw65EuP3BVQSHqaz9eBzLesbf8YAi0IhoJRXgRo9kjX6HaEecgucOjLmXpknMmyNgwXKNl/6hMIkAQ==,iv:ZH9vom4jt0CJ5V2L7r2CvR7Lu5Rd2jRPYtag6Gm6Nkg=,tag:CkxFce+kCny6Jb3aSYQUKQ==,type:str]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:w4/tFp/A2SCVLmuNWtgMh/FKzIj+rVs=,iv:tD3YXrmsT4EtHAhW1Lts5iR//T6IvrO4ygkGG29uoJQ=,tag:EY9fRaqrmjDXhBoZPFnxiw==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:tAyajUH0Bg==,iv:4fGvu9FTtvbPTIqSmlVANjZJLUbo2picj+4t7Q1vm1c=,tag:zPUTmc3ET8KjPzoPUl7JIQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:lED7g0V20R3+wc29,iv:IdBopfDa9Fr2g/if2Aho/3OKOdWPNEnV6sTMlX0e0k8=,tag:XWbdU2+od3uqkoWyw2zbOg==,type:str]
    OPENWEBUI_SECRET_KEY: ENC[AES256_GCM,data:1OWslnpyxrCjf9wnVnjBpaxaRGwO+qc5JvXXgYtVLHs7QxJSmVpLfkazwDA+xMvWsfWDxu5XW6JMJylzcxJ/cQ==,iv:JjRE3r1Ob5J+uvGiv+ptO8ACeujy4onAcO4ZBWgyz9w=,tag:05jDDsMf4id/C7FGpKG3XQ==,type:str]
    COMMANDCODE_API_KEY: ENC[AES256_GCM,data:5NNXVxDhihEtpFLy4DkoLZq2qwdpKYsS1lP7UHax3GJHxIg4cb2iTfVGDAJpgVsQ64ib1EAYmD/zaX1iCJwWWGjtS0kEMeIhwkaeddLUkfHcI63x6wf9af6z5C6m,iv:uW3inNX11btZdLWkfmk5rECwBcqjxPRhNaEzG5FfeZs=,tag:1+zaYZX3/lfaeZuMQmCeWg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:mIYRpp6YJvHEMTifxxifaVDsrP4uY47bRFoLnESCyDRYHC4hNOX0qkgOMepDD8OczKnrfRH2HuoiqHZETDZlZw==,iv:6PEgr84K19KxI+0GA26kizvzQWSVYArjInrgjMRF+2A=,tag:FKofzmOdobZKJ09tSOLs8A==,type:str]
    WEATHER_LOCATION: ENC[AES256_GCM,data:Q4hKjp6ay0tShMUJmcz/JTKozssrpIqVXqyCvJhQ6uZa/q8gVA==,iv:aBbPqIhD3gbhLkVlfRqJXRUtGWUuWsTUFozpkipW4lI=,tag:2cJcvqs/7sUYkiTksZ5tWQ==,type:str]
    AIOSTREAMS_AUTH_USER: ENC[AES256_GCM,data:fnIDrX7Tm+dxRw==,iv:F5I2bvUqXjgS8qHsW6Ti/8ayJ3abybGqoXmVggve9G8=,tag:6ILl+he6/jzktZllXutwGA==,type:str]
    AIOSTREAMS_AUTH_PASSWORD: ENC[AES256_GCM,data:lOV4fUEKLC9xuGwO,iv:JZIbqFCFDDdGbWEheB7ARxZLpzta66CZ/wPQI7w+6Gs=,tag:GXRhZRrXUeh3YzA5c+aLcA==,type:str]
    PROXMOX_TOKEN: ENC[AES256_GCM,data:EeID09E1ncJVGUfiFAOgzsk8YXkaX7zLXgDmLZb3JtkoEZEK8N/dk46b6JJVck0L4xoS3F7R,iv:FjrOuRc3aWpZhmjxetsixwnmhDvgM+jCxoH9xA9ZnNk=,tag:Qv0FAttXfE6S3dSdRiY6CQ==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:D4p5f4bT6aMJV5S1DADLymut42AuJQV/zxjMCZWWolE=,iv:BGlq03GY6XSbxZIp/DObzqWaguIKxXY4o44bnQ2N5qg=,tag:ycqKdl6mGC/odP0l1pBSMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWGMwa0hzNVhsMWV6SFRN
            WUc1VEoySWJkMmp4TDBaQW01eWZOblkxMVQwCllFRmQySm4rWUdqaEo1YTk5MkVm
            alY2UndsMnJXbXAyS2ZpbzMweVV4ckkKLS0tIGIzWGlkZkFZazIvcVc4bnlRcjhq
            OXZVcVA2ZzJDTW1nUGRNc1A3cUZIUEEKZgtFOliNI7eI5lDkoKz0dwFENAq+c3U+
            1HPhET6IY2srhod99T8gXuCxcoFmvt8zyx4ICtbBY/o/PPl6wCeJhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T06:33:58Z"
    mac: ENC[AES256_GCM,data:JR7TwNytNYmxJUpyWOa0e4S8mwVCD2YScARIK9GIesuWLZmOdkFSh8DmhCLPDfbxCIBx0SmzfWI5I9PJqZe2P+gEHQSXm3m0ukE/tpDResEbpoXruqzEJnJ9YAdwroxmaTlEbcMlOzRxiu2qX3P024CYcjrSZ2tprpdzTOZczh8=,iv:r3594ZdJqvcoYytD/2qBv2pOkci+qdnvnQxd6Nzth0U=,tag:DYFBERVpIGj7rxp4kqvhkQ==,type:str]
    version: 3.13.3
