apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: services
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:ZSFEbkduCG2WDf/6/6zDJ4lIGu5KZyTxM4GQc2Adu3nGfiA/RoXR+jXuz6c=,iv:bx4nqpX9cJf7jTiGQ2bShJ/RTTnbcgnO7oRa3769SzI=,tag:mzHCYY1lMMS2ZxpMOm2Oog==,type:str]
    OPENAI_API_KEYS: ENC[AES256_GCM,data:7EjH9MWJlHU0VE1pbnH+4IU5PYf3SRYnWL/180dGpH90VMfWHL14mC+FfWoEQIbWaKe7EkfURZo1n+cP43T4f8LIHZZXqglluzcT971JxFQFK86zmEQ+X1HHqfYE,iv:MeZdbV/pv7MNxo4fZoLLx0nzw2n3ukZJGStwNMkV7zQ=,tag:HV4+spqBhI4AGJ/BoMi2wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXM4MlFsQTQybk9xSWtC
            aVJEanMvZVRhWGJwY1EvUkN0YWNPdWNrZUdFCkY4bDJzVUdLRDY3TklYdWxmWGNy
            ZW5LMUNwQlZhYWZraUdKOHA1UmorRVUKLS0tIEFPVDUxa2dIcW4vTmpXaEJlS00x
            cGlvVnRaTXNJVlhRQmMxcVFnclNoNDgKRxckg9Cmt/eqBMvuaEZ6sSx4IZckXXKr
            ZqSAPqv8gsox1SEgbBwfbX1DtUagLH/th60RErZVxLug9oMj1q5XiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T15:55:27Z"
    mac: ENC[AES256_GCM,data:8guIjEHQhHNCkQ3pSS0WC6OXgiQTQEfIZ/7ngdr3pT82M3hasAFUssj/I/lGrmi9Ym1iTUUIxYmT0bFuPejiUAjfm/UuiGlVX/T1KUjUzIb4wrRhSCc5dTTlaVpMno4hEQkVdAxg54xAHVE41OBTlDPv35KbrdyDxAZZwjk4G2M=,iv:RaPl7un1EIYkk5dysjgs/yvjOsdSKSGHPpfulUGUlb4=,tag:ZjKNrgVd7FfVBDK0w3buUg==,type:str]
    version: 3.13.3
