apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - aiostreams
  - aiomanager
  - aiometadata
  - comet
  - knightcrawler
  - mediaflow-proxy
  - mediafusion
  - nzbdav
  - prowlarr
  - spottarr
  - stremthru
  - subtitles
  - uptime-kuma

