apiVersion: v1
kind: Service
metadata:
  name: stalker-stremio
  labels:
    app.kubernetes.io/name: stalker-stremio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stalker-stremio
  ports:
    - name: http
      port: 7000
      targetPort: http
