apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:UvZaO/utE1rwR5j0hcJN93OY5bsNVdQt+YHwpQgrQetXiHomoF7W2nHdDOKuZv+Ch+cTAIljRrGo/KWSFgfWtg9V6IIL7XloaUKfoHXPD5NCnCwaNV+Ndr7rX1AggHxK7Ijy9cPqS7ap1PR+sjmlDQJgqTefW7/TDppP+MOQjHtUCFr+y5DOIXDbMfLuZugqfFGCX16StT7moR3l,iv:NrPta0wJFOJyOFnIm95xXEeOFVO9q91YcVgxGYXB1yI=,tag:0mzGEMiD+VBwGGvJ4N4ZEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOTcyMUZDSW90ZE1MbFJk
            MXFxZ3dadXpRWU51NUtsaDNOOTQ3RWMxR1UwCmE2MXV4dFE0VndSYUZoNUVRMEQ2
            REN5OXA4ZzZHMUlhZjZ4MzdZTDVTMzAKLS0tIDhPQktDbkE5S01VV1ZtZDJVWlpQ
            cWNyeUk2cDdMcFljUW1yZ3p1M2Y1aGMKqbRpM7o+nF8+B4/eY/m2/w3108ERps8n
            euQDe75wUMqskbfz9OGz2tpqK+BZGHBqHSXFHfGZPZ5UVsVDGkWipg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T09:43:25Z"
    mac: ENC[AES256_GCM,data:NQBSBaVQyQyvKB2AjRgJX1cOXGrN89yBjHg67qJc2zB2OmNcaWq4VAuOsONG2I5DG7YwMfumhc3QjDlPhiPyn0iRV/blSSDE3Y8kI9AhTCP+Scsh8N/0kQZ10XEFsWk9ZQdYxzLF6FRdV12F3/SHXQsRH2vwKvDMVZBpU/cpbyI=,iv:hn+DHJ3d29SOMCPwCgL+S2cO0BU0XkZUyLn6O31GmrI=,tag:qiDLBnlYHgaBnlBubgO0HQ==,type:str]
    version: 3.13.3
