#!/usr/bin/env bash
# Generates cilium-install.yaml: the CRDs plus the Cilium chart, as one manifest
# that the Omni cluster template applies.
#
# The output is in git, so a fresh bootstrap needs no helm and no network. Run
# this only when you want to upgrade Cilium:
#
#   ./generate.sh                      # version below
#   CILIUM_VERSION=1.20.3 ./generate.sh
#
# Deliberately one file: the CRDs have to exist before the chart, and within one
# manifest the order is guaranteed.
set -euo pipefail
cd "$(dirname "$0")"

CILIUM_VERSION="${CILIUM_VERSION:-1.20.2}"
CRD_OWNER="cilium/cilium"
CRD_PATH="pkg/k8s/apis/cilium.io/client/crds/v2"
CRD_REF="v${CILIUM_VERSION}"
OUT="cilium-install.yaml"

command -v helm >/dev/null || { echo "helm is missing" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 is missing" >&2; exit 1; }

tmp="$(mktemp -d)"; trap 'rm -rf "${tmp}"' EXIT

echo "== Fetching the CRDs from ${CRD_OWNER} ${CRD_REF} =="
names="$(curl -sS --fail \
  "https://api.github.com/repos/${CRD_OWNER}/contents/${CRD_PATH}?ref=${CRD_REF}" \
  | python3 -c "import sys,json;print('\n'.join(sorted(x['name'] for x in json.load(sys.stdin) if x['name'].endswith('.yaml'))))")"
for n in ${names}; do
  curl -sS --fail -o "${tmp}/${n}" \
    "https://raw.githubusercontent.com/${CRD_OWNER}/${CRD_REF}/${CRD_PATH}/${n}"
done

echo "== Rendering the Cilium chart =="
helm repo add cilium https://helm.cilium.io/ >/dev/null 2>&1 || true
helm repo update cilium >/dev/null

{
  echo "# Generated by omni/cilium/generate.sh, do not edit by hand."
  echo "#"
  echo "#   cilium : ${CILIUM_VERSION}"
  echo "#   CRD's  : github.com/${CRD_OWNER} ${CRD_REF}, ${CRD_PATH}"
  echo "#   values: omni/cilium/values.yaml"
  echo "#"
  echo "# First the CRDs, then the chart. The Cilium Helm chart contains no"
  echo "# CRDs (helm show crds returns 0 lines). Without these files"
  echo "# CiliumNetworkPolicy does not exist and the policy layer silently does nothing."
  echo ""
  echo "# ---------------------------------------------------------------- CRD's"
  for f in "${tmp}"/*.yaml; do
    echo "---"
    cat "${f}"
  done
  echo ""
  echo "# ------------------------------------------------------------- Cilium"
  helm template cilium cilium/cilium --version "${CILIUM_VERSION}" \
    --namespace kube-system -f values.yaml
} > "${OUT}"

# Catch the two mistakes that really hurt on Talos.
crd_count="$(grep -c '^kind: CustomResourceDefinition' "${OUT}")"
[ "${crd_count}" -gt 10 ] || { echo "too few CRDs (${crd_count})" >&2; exit 1; }
grep -q 'ciliumnetworkpolicies' "${OUT}" || { echo "ciliumnetworkpolicies is missing" >&2; exit 1; }
grep -q 'enable-host-legacy-routing: "true"' "${OUT}" || {
  echo "enable-host-legacy-routing is missing; on Talos DNS does not work without it" >&2; exit 1; }
grep -q 'ipam: "kubernetes"' "${OUT}" || { echo "ipam is not set to kubernetes" >&2; exit 1; }
if grep -q "SYS_MODULE" "${OUT}"; then
  echo "SYS_MODULE is still in the capabilities; Talos refuses that" >&2; exit 1
fi

echo "   ${OUT}: ${crd_count} CRDs, $(wc -l < "${OUT}") lines"
echo "done"
