apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
spec:
  selector:
    app.kubernetes.io/name: guacd
  ports:
    - name: guacd
      port: 4822
      targetPort: guacd
