# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aiostreams.yaml
  - ./aiometadata.yaml
  - ./aiomanager.yaml
  - ./catch-all.yaml
  - ./certificate.yaml
  - ./comet.yaml
  - ./coder.yaml
  - ./flux-operator.yaml
  - ./grafana.yaml
  - ./hermes-agent.yaml
  - ./homeassistant.yaml
  - ./homeassistant-k8s.yaml
  - ./knightcrawler.yaml
  - ./longhorn.yaml
  - ./mediaflow-proxy.yaml
  - ./mediafusion.yaml
  - ./middlewares.yaml
  - ./nexus.yaml
  - ./nzbdav.yaml
  - ./obsidiansync.yaml
  - ./oauth2-proxy.yaml
  - ./prowlarr.yaml
  - ./spottarr.yaml
  - ./stremthru.yaml
  - ./subtitles.yaml
  - ./traefik.yaml
  - ./uptime-kuma.yaml
  - ./velero-ui.yaml
  - ./zigbee2mqtt.yaml
