# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aiostreams.yaml
  - ./catch-all.yaml
  - ./certificate.yaml
  - ./chacdn.yaml
  - ./control.yaml
  - ./flux-operator.yaml
  - ./frigate.yaml
  - ./grafana.yaml
  - ./guacamole.yaml
  - ./hermes-agent.yaml
  - ./homeassistant.yaml
  - ./homeassistant-k8s.yaml
  - ./keycloak.yaml
  - ./longhorn.yaml
  - ./middlewares.yaml
  - ./nexus.yaml
  - ./obsidiansync.yaml
  - ./oauth2-proxy.yaml
  - ./spottarr.yaml
  - ./traefik.yaml
  - ./uptime-kuma.yaml
  - ./velero-ui.yaml
  - ./zigbee2mqtt.yaml
