apiVersion: v1
kind: Secret
metadata:
    name: telegram-notification
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:mdMJKjtcIA3HWVrMzwDstcHdUO67902y1/hPEiWxVXIpFlhLs2vCgB4ZM1FDTw==,iv:9oONPnyzT9043bHwmibfsyI9vP+ZmaXf1p2uehkuNg4=,tag:PqkWQ79wMYXqLy33AL46cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aCtZdGcyQjVHeG5wZnNx
            STd3TU9RbnhVa24vTDllT3E4OTNlQi9FRUVRCm5MdUczTndCeTlveVVXL0hCQkpp
            a1Nkd1J6WDUzeU9wMEx4UnhxZnNiaXcKLS0tIGRzaGdHOXd3ZUpYQUw3SkZEVXp2
            ZXFlczlOaW9wRnJNNGk3djRsa3NZeGsKNP1epO+Oby23IHOmOFAmRI7utwuJlySI
            rTP86VsAlS+77x/yrXJ/OEEhzMzKnWundG9wefa9rbgOAzyT6kj72w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T08:33:54Z"
    mac: ENC[AES256_GCM,data:aZdNqijcx+rC60uvS5qoNGSghiXHSIQQnN+vuI79ejW5KRHrhPv56NFytAS5wsQqJmcUK5dTkwyJpmy8Sp8PU8u7dnsQhJNfDjSZnNtIXSssz6BA6jdjwbMJAKGusTTZzSfJi/GLV8hWmnbl80xPobL2Od+fJIcjCXRy6P/3lDM=,iv:afHcZFRmnMXUxdgPsXQwDgTqbm5LsUOBj1HqXrPlWf8=,tag:mOo2zWAQXZkKff8wYFwdJA==,type:str]
    version: 3.13.3
