# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secret
    namespace: services
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:KkM6K9V9irEapuMQ6HQkKfjPXUlGkqlbjOXskACIuQTTanCMJCzFLa4EW793AHlrBiI2j7ZfM4IziB/6fzLBpA==,iv:8cI9+zWs2jPMIFro0//+V36WVhLI66T3F+EPB26/Qhk=,tag:M+qN9NtepfSeKtTLatKuYQ==,type:str]
    ADDON_PASSWORD: ENC[AES256_GCM,data:Xz6yJVW+QlslgbZV,iv:tvvgE9k8bVBOXkUQGxy+2rWI8/AqD5/mjhTVRevUrok=,tag:bOVK8ykAFLu8/AEtUneWNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dExWaTFuMWYxL0J1UEZ2
            dll0b2xJWWtmR3lySm56WjNQZ0dxTEo1bUJjCjlHQW50bE55YkRKZTZQa3hISG8v
            WWd6cUNPVjR6Z3lKK2JtcXk2aUg0aFkKLS0tIE5EclB2NzVvQW5ENW40M0dHUndN
            SndtTjg3QmdrcS93VS96NStFU293cnMKLjm29HHxkkX6LhM4zGXzEYtV6b7lTWLL
            qgzEQ+p4qDINOlEU81uF8vQ99Z1FSOWJpP5FcuEZvGVX34rtpf9nXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T14:39:27Z"
    mac: ENC[AES256_GCM,data:nVKSCvebrqPHcqtKKoEHdWEs9iQg4DYyJ7YidjxFZZVtRy7LAw35zEvx6V82UB3XsKjgNpAFWk2C3MZ/wXKVhEQ+vHVZcG1Hs6A3yMEu+gHOIB0N1g0QsWNKBrFl3LrExVsmgoOBaU3E4uQ1AKboMuV51w6bUhf53bnXJpUN8+I=,iv:i2OIa/mhBn76sbGZBQcBSqjsU1nStFqvJrkbHasQ3fk=,tag:IdmsGkcbzFOi1FxF6sNLxQ==,type:str]
    version: 3.11.0
