apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbdav
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nzbdav
  values:
    controllers:
      nzbdav:
        containers:
          app:
            image:
              repository: nzbdav/nzbdav
              tag: alpha
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "${TZ}"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              capabilities:
                add: ["CHOWN", "SETGID", "SETUID"]
                drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 3000
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /config
